"""
Django settings for vvip project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import ast
import os
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+40=cx1=%@eo4w-1v663)&kp$+-^cd20#ki0r2%l5uur2_ln)5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'v_search',
    'users',
    't_search',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
]

REST_FRAMEWORK = {
    "PAGE_SIZE": 100,
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular API網頁顯示設定
SPECTACULAR_SETTINGS = {
    'TITLE': 'vvip',
    'DESCRIPTION': 'vvip',
    'VERSION': '0.0.1',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'], # 預設權限
    # OTHER SETTINGS
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vvip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# SITE_ID = 1996
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend"
)

SOCIALACCOUNT_PROVIDERS = {
    'line': {
        "SCOPE": ['profile', 'openid', 'email']
    }
}

ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_CONFIRMATION_HMAC = False
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_MAX_EMAIL_ADDRESSES = 1
ACCOUNT_LOGOUT_ON_GET = True

ACCOUNT_ADAPTER = 'users.forms.NoNewUsersAccountAdapter'

WSGI_APPLICATION = 'vvip.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}

DATABASE_ROUTERS = ['vvip.db_router.DatabaseAppsRouter']
DATABASE_APPS_MAPPING = {
    # example:
    # 'app_name':'database_name',
    #'carinfo',
    # 'bigdata': 'bigdata',
    # 'developement': 'land_data',
    # 'use_zone': 'land_data',
    # 'users': 'land_data',
    # 'ssapis': 'land_data',
    # 'build_data': 'build_data',
    # 'community': 'build_data',
    # 'lvr_land': 'lvr_land',
    't_search': 'diablo_test',
    # 't_search': 'diablo',
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True

from django.conf.locale.zh_Hant import formats as zh_hant_formats

zh_hant_formats.DATETIME_FORMAT = "Y-n-j H:i:s"
zh_hant_formats.DATE_INPUT_FORMATS[0] = "%Y-%m-%d"
zh_hant_formats.TIME_INPUT_FORMATS[0] = "%H:%M:%S"
zh_hant_formats.DATETIME_INPUT_FORMATS[0] = "%Y-%m-%d %H:%M:%S"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1", # 指定redis://IP/第幾個DB
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        'KEY_PREFIX': 'Cache'
    }
}


BIGDATA_HOST = 'https://104.yeshome.net.tw'


try:
    from local_settings import *
except ImportError:
    pass


LOG_LEVEL = 'INFO'
if DEBUG == True:
    LOG_LEVEL = 'DEBUG'

if not os.path.exists('logs'):
    os.makedirs('logs')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'normal': {
            'format': '[%(levelname)s] %(asctime)s | %(name)s:%(lineno)d | %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'normal',  # use the above "normal" formatter
            # 'rich_tracebacks': True,  # 錯誤訊息框架
            # 'filters': ['require_debug_true'],  # add filters
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/main.log',
            'maxBytes': 1024*1024*10,
            'backupCount': 10,
            'formatter': 'normal',
        }

    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'v_search': {  # means "root logger"
            'handlers': ['console', 'file'],  # use the above "console" handler
            'level': LOG_LEVEL,  # logging level
        },
        # 'common': {  # means "root logger"
        #     'handlers': ['console', 'file'],  # use the above "console" handler
        #     'level': LOG_LEVEL,  # logging level
        # },
        # 'land': {  # means "root logger"
        #     'handlers': ['console', 'file'],  # use the above "console" handler
        #     'level': LOG_LEVEL,  # logging level
        # },
        # 'user': {  # means "root logger"
        #     'handlers': ['console', 'file'],  # use the above "console" handler
        #     'level': LOG_LEVEL,  # logging level
        # },
        # 'extra_building': {  # means "root logger"
        #     'handlers': ['console', 'file'],  # use the above "console" handler
        #     'level': LOG_LEVEL,  # logging level
        # },
        # 'extra_common': {  # means "root logger"
        #     'handlers': ['console', 'file'],  # use the above "console" handler
        #     'level': LOG_LEVEL,  # logging level
        # },
        # 'extra_land': {  # means "root logger"
        #     'handlers': ['console', 'file'],  # use the above "console" handler
        #     'level': LOG_LEVEL,  # logging level
        # },
    },
}



